### ISSUE TITLE
Temp Shulker

### ISSUE THREAD

**Issue by iiegit** [TBMCPlugins/AliPresents#2]
summon shulker at player, with:

-10 health

-Wither 5 effect

-Invisibility effect

-0 experience drop on death

I've been good all year Santa

**Comment by alisolarflare** [comment]
I'll limit it to just you, making it /AliShulker [health] [wither effect] [invisibility] [experiencedrops]

**Comment by alisolarflare** [comment]
I set the potions to work for 24 hours, if you need longer, let me know

**Comment by NorbiPeti** [comment]
(I just realized who is iiegit. My mind basically just skipped that name without parsing it...)

**Comment by alisolarflare** [comment]
_neeeat_

**Comment by alisolarflare** [comment]
AliShulker Thrown in the Graveyard
