### ISSUE TITLE
AND I SAID HEEEEEEEEEEEYEEEEEEEEEEEEYEEEEYEEYEE

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/AliPresents#47]
# And so I cry sometimes when I'm lying in bed
Just to get it all out what's in my head
And I, I'm feeling a little peculiar

And so I wake in the morning and I step outside
And I take a deep breath and get real high
And I scream from the top of my lungs
What's goin' on?

And I say hey, yeah, yeah, yeah yay
Hey, yay, yay
I said hey, what's goin' on?

And I say hey, yeah, yeah, yeah yay
Hey, yay, yay
I said hey, what's goin' on?

And he tries
Oh my God, do I try
I try all the time,
In this institution

And he prays
Oh my God, do I pray
I pray every single day
(Nyaaah)
For a revolution!

And I say hey, yeah, yeah, yeah yay
Hey, yay, yay
I said hey, what's goin' on?

And I say hey, yeah, yeah, yeah yay
Hey, yay, yay
I said hey

(Don't cry out loud)
(Just keep it inside
and learn how to hide your feelings)

(Hey, yeah, yeah, yeah yay)
(Hey, yay, yay)
Hey hey hey
I say hey
What's goin' on?
Yeah!

**Comment by NorbiPeti** [comment]
*What*

**Comment by NorbiPeti** [comment]
W h a t
