### ISSUE TITLE
worldguard and worldedit with command blocks

### ISSUE THREAD

**Issue by iiegit** [TBMCPlugins/AliPresents#5]
if you can find a way, this one seems trickier than the others

**Comment by alisolarflare** [comment]
@iie, are you still interested in this feature?

**Comment by iiegit** [comment]
yes definitely

**Comment by alisolarflare** [comment]
@iiegit not really sure how I'd go about this... we could customize WorldGuard, and have our own WorldGuard plugin with edited methods, if you'd like. Either way, I doubt I can affect the permissions through AliPresents alone
